IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Doctor'))
BEGIN;
    DROP TABLE [Doctor];
END;
GO

CREATE TABLE [Doctor] (
    [ID] INTEGER NOT NULL,
    [FirstName] VARCHAR(255) NULL,
    [SendName] VARCHAR(255) NULL,
    [Surname] VARCHAR(255) NULL,
    [Speciality] NVARCHAR(255) NULL,
    [Category] INTEGER NULL,
    PRIMARY KEY ([ID])
);
GO

INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (1,'Quamar','Timon','Blevins', N'терапевт',3),(2,'Randall','Aladdin','Scott', N'ЛОР',2),(3,'Kyle','Alvin','Cook', N'ЛОР',2),(4,'Adrian','Quentin','Paul', N'хирург',3),(5,'Francis','Acton','Nguyen', N'терапевт',1),(6,'Raphael','Mufutau','Clements', N'хирург',1),(7,'Jonah','Lee','Ferrell', N'терапевт',2),(8,'Byron','Dominic','Yates', N'ЛОР',2),(9,'Jerry','Aaron','Berry', N'хирург',3),(10,'Benjamin','Cruz','Simon', N'терапевт',2);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (11,'Gage','Avram','Diaz', N'терапевт',2),(12,'Merrill','Dalton','Guerra', N'терапевт',1),(13,'Austin','Magee','Meyers', N'терапевт',2),(14,'Walker','Deacon','Francis', N'хирург',1),(15,'Logan','Fitzgerald','Hester', N'хирург',1),(16,'Gregory','David','Conrad', N'хирург',3),(17,'Cain','Colton','Cherry', N'хирург',1),(18,'Ivor','Ezra','Flowers', N'терапевт',2),(19,'Boris','Kato','Jensen', N'хирург',1),(20,'Lyle','Timon','Mendoza', N'терапевт',3);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (21,'Alexander','Cairo','Brock', N'хирург',2),(22,'Tanek','Omar','Guzman', N'терапевт',1),(23,'Rigel','Walker','Sampson', N'хирург',2),(24,'Guy','David','Barron', N'ЛОР',1),(25,'Zeph','Marvin','Barnett', N'ЛОР',1),(26,'Herman','Scott','Sellers', N'хирург',3),(27,'Macaulay','Curran','Mccullough', N'терапевт',3),(28,'Caesar','Kasimir','Bush', N'терапевт',3),(29,'Elijah','Rigel','Nolan', N'терапевт',1),(30,'Christian','Benjamin','Schroeder', N'терапевт',2);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (31,'Raymond','Aidan','Greer', N'ЛОР',3),(32,'Merritt','Keith','Buckley', N'хирург',3),(33,'Merritt','Slade','Holt', N'хирург',2),(34,'John','Graiden','Gaines', N'терапевт',2),(35,'Zane','Felix','Beard', N'ЛОР',2),(36,'Perry','Camden','Hopkins', N'терапевт',3),(37,'Guy','Rafael','Serrano', N'хирург',1),(38,'Felix','Cyrus','Delgado', N'хирург',2),(39,'Keaton','Levi','Rogers', N'хирург',3),(40,'Kasimir','Nathan','Morales', N'терапевт',1);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (41,'Talon','Kelly','Weeks', N'хирург',2),(42,'Thomas','Preston','Hayes', N'ЛОР',2),(43,'Alec','Baxter','Blanchard', N'хирург',1),(44,'Ethan','Gil','Holt', N'ЛОР',1),(45,'Austin','Wing','Mckinney', N'хирург',1),(46,'Oren','Drake','Richmond', N'хирург',2),(47,'Timon','Uriel','Holman', N'терапевт',2),(48,'Amir','Colin','Hendricks', N'терапевт',1),(49,'Brady','Clarke','Patton', N'терапевт',1),(50,'Barrett','Sawyer','Norris', N'хирург',2);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (51,'Bernard','Brady','Love', N'хирург',1),(52,'Ian','Garrett','Hamilton', N'ЛОР',3),(53,'Duncan','Christopher','Odonnell', N'терапевт',1),(54,'Fulton','Brady','Rowe', N'хирург',2),(55,'Myles','Lawrence','Hale', N'хирург',1),(56,'Paul','Malcolm','Donovan', N'терапевт',1),(57,'Abel','Jared','Wilkins', N'хирург',2),(58,'Nolan','Xander','Morton', N'хирург',1),(59,'Davis','Sebastian','Rhodes', N'ЛОР',1),(60,'Jakeem','Camden','Weaver', N'терапевт',1);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (61,'Sebastian','Eaton','Kennedy', N'терапевт',3),(62,'Kennedy','Arden','Vaughn', N'терапевт',1),(63,'Theodore','Lewis','Price', N'ЛОР',3),(64,'Colby','Armando','Sherman', N'хирург',1),(65,'Jesse','Kane','Hyde', N'ЛОР',2),(66,'Gavin','David','Waller', N'ЛОР',2),(67,'Denton','George','Pearson', N'ЛОР',2),(68,'Hyatt','Melvin','Kramer', N'ЛОР',1),(69,'Troy','Alec','Castaneda', N'хирург',3),(70,'Austin','Gray','Larson', N'ЛОР',1);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (71,'Jerome','Rudyard','Villarreal', N'хирург',3),(72,'Igor','Darius','Nelson', N'терапевт',2),(73,'Zane','Phillip','Chapman', N'ЛОР',2),(74,'Devin','Guy','Gardner', N'хирург',3),(75,'Dustin','Gannon','Blanchard', N'ЛОР',3),(76,'Erich','Kelly','Stanton', N'терапевт',3),(77,'Tucker','Arthur','Stephenson', N'ЛОР',3),(78,'Erich','Davis','Michael', N'ЛОР',3),(79,'Kane','Levi','Webster', N'хирург',1),(80,'Demetrius','Bruce','Hickman', N'ЛОР',1);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (81,'Clarke','Troy','Mccarty', N'хирург',3),(82,'Price','Ulysses','Fuller', N'хирург',1),(83,'Chadwick','Asher','Fitzpatrick', N'терапевт',3),(84,'Amery','Prescott','Burton', N'хирург',3),(85,'Wyatt','Kennedy','Greer', N'терапевт',3),(86,'Baxter','Theodore','Barber', N'ЛОР',1),(87,'Reese','Simon','Pace', N'хирург',1),(88,'Octavius','Moses','Horne', N'ЛОР',2),(89,'Edward','Hunter','Meyers', N'хирург',3),(90,'Reuben','Myles','Walker', N'терапевт',1);
INSERT INTO Doctor([ID],[FirstName],[SendName],[Surname],[Speciality],[Category]) VALUES (91,'Kuame','Bevis','Conrad', N'терапевт',1),(92,'Malachi','Carter','Ferguson', N'ЛОР',1),(93,'Rudyard','Rashad','French', N'терапевт',1),(94,'Edan','Ian','Monroe', N'ЛОР',1),(95,'Deacon','Zeus','Patterson', N'ЛОР',2),(96,'Harrison','Timothy','Weber', N'ЛОР',3),(97,'Warren','Jared','White', N'хирург',1),(98,'Gregory','Moses','Boyle', N'ЛОР',2),(99,'Jermaine','Brock','Love', N'терапевт',2),(100,'Galvin','Cadman','Santana', N'ЛОР',2);